### ISSUE TITLE
Can't build with Xcode 13.3 beta

### ISSUE THREAD

**Issue by RobotK** [apollographql/iOSCodegenTemplate#13]
When I try and build with the Xcode 13.3 beta, I get the following error:
>Library/Developer/Xcode/DerivedData/ApolloCodegen-bpkqdjekiwtugdbvjsrvflrfnjtd/SourcePackages/checkouts/apollo-ios/Sources/ApolloCodegenLib/Frontend/JavaScriptBridge.swift:9:14: error: 'Sendable' class 'JavaScriptError' cannot inherit from another class other than 'NSObject'
public class JavaScriptError: JavaScriptObject, Error {

**Comment by calvincestari** [comment]
The [`Sendable`](https://developer.apple.com/documentation/swift/sendable) protocol appears to be part of Swift Concurrency; iOS 15+ and Xcode 13+. I wonder if the 13.3 beta has something misconfigured that is causing the compiler error - I get the same error. Could have something to do with concurrency back porting to iOS 13?

I'm going to close this issue for now, given that it's in the first beta, but if this persists in future beta releases please reopen and we'll take another look at it.

**Comment by brayden4012** [comment]
@calvincestari I'm still seeing this issue on the official Xcode 13.3 release
Update: Nevermind, I haven't updated Apollo. let me give that a try

**Comment by calvincestari** [comment]
Thanks for checking.

I was just going to say that I use 13.3 (13E113) daily without issue. I'm putting up a PR now to update CircleCI to use 13.3 too so we can be sure it's working everywhere and not only in our environments.

**Comment by braydenharris** [comment]
Yeah sorry about that. We had to fork your repo in order to strip `null` values for change streams
